name: jupyter-base
channels:
    - default
    - conda-forge
dependencies:
    - python=3.8
    - requests
    - dnspython
    - arrow>=1.0
    - scikit-learn==0.22
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pweave
    - spyder
    - jupyter
    - ipywidgets
    - jupyterlab
    - jupyter_contrib_nbextensions
    - jupyterlab-git
    - asyncpg
    - aiohttp

